[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT cyprus_api.wsgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
